// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChat_data = "chat_data"

// Chat_data mapped from table <chat_data>
type Chat_data struct {
	ID        int64   `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Msgid     string  `gorm:"column:msgid;type:varchar(255);not null;comment:消息id，消息的唯一标识，企业可以使用此字段进行消息去重" json:"msgid"`                                           // 消息id，消息的唯一标识，企业可以使用此字段进行消息去重
	Action    string  `gorm:"column:action;type:varchar(10);not null;comment:消息动作，目前有send(发送消息)/recall(撤回消息)/switch(切换企业日志)三种类型" json:"action"`                    // 消息动作，目前有send(发送消息)/recall(撤回消息)/switch(切换企业日志)三种类型
	From      string  `gorm:"column:from;type:varchar(255);not null;comment:消息发送方id。同一企业内容为userid，非相同企业为external_userid。消息如果是机器人发出，也为external_userid" json:"from"` // 消息发送方id。同一企业内容为userid，非相同企业为external_userid。消息如果是机器人发出，也为external_userid
	Tolist    *string `gorm:"column:tolist;type:json;comment:消息接收方列表，可能是多个，同一个企业内容为userid，非相同企业为external_userid" json:"tolist"`                                    // 消息接收方列表，可能是多个，同一个企业内容为userid，非相同企业为external_userid
	Roomid    string  `gorm:"column:roomid;type:varchar(255);not null;comment:群聊消息的群id。如果是单聊则为空" json:"roomid"`                                                    // 群聊消息的群id。如果是单聊则为空
	Msgtime   int64   `gorm:"column:msgtime;type:bigint(20);not null;comment:消息发送时间戳" json:"msgtime"`                                                              // 消息发送时间戳
	Msgtype   string  `gorm:"column:msgtype;type:varchar(255);not null;comment:文本消息为" json:"msgtype"`                                                              // 文本消息为
	URL       *string `gorm:"column:url;type:varchar(255)" json:"url"`
	Info      *string `gorm:"column:info;type:text" json:"info"`
	Metadata  *string `gorm:"column:metadata;type:json" json:"metadata"`
	CreatedAt *int64  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt *int64  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	DeletedAt *int64  `gorm:"column:deleted_at;type:int(11)" json:"deleted_at"`
}

// TableName Chat_data's table name
func (*Chat_data) TableName() string {
	return TableNameChat_data
}
